context:
  version: 0.9.8

package:
  name: joshuto
  version: ${{ version }}

source:
  url: https://github.com/kamiyaa/joshuto/archive/v${{ version }}.tar.gz
  sha256: 877d841b2e26d26d0f0f2e6f1dab3ea2fdda38c345abcd25085a3f659c24e013

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - joshuto --help

about:
  license: GPL-3.0-or-later
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: ranger-like terminal file manager written in Rust
  homepage: https://github.com/kamiyaa/joshuto
  repository: https://github.com/kamiyaa/joshuto

extra:
  recipe-maintainers:
    - danielnachun
